# Generated by Django 5.0.6 on 2026-06-06 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'catalog_genres',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la Sala')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('layout_json', models.JSONField(verbose_name='Distribución de Butacas (JSON)')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'catalog_rooms',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('director', models.CharField(max_length=150, verbose_name='Director')),
                ('duration_min', models.IntegerField(verbose_name='Duración (min)')),
                ('rating_classification', models.CharField(choices=[('ATP', 'Apta para Todo Público'), ('+13', 'Mayores de 13'), ('+16', 'Mayores de 16'), ('+18', 'Mayores de 18')], max_length=10, verbose_name='Clasificación')),
                ('release_date', models.DateField(verbose_name='Fecha de Estreno')),
                ('poster_url', models.URLField(blank=True, max_length=500, verbose_name='URL del Póster')),
                ('trailer_url', models.URLField(blank=True, max_length=500, verbose_name='URL del Tráiler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa en Cartelera')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(db_table='catalog_movie_genres', to='catalog.genre', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'db_table': 'catalog_movies',
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Horario de Inicio')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Función Activa')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='catalog.movie', verbose_name='Película')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='catalog.room', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'db_table': 'catalog_screenings',
            },
        ),
    ]
