# Generated by Django 5.0.6 on 2026-06-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_auditlog_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screening',
            options={'ordering': ['-start_time'], 'verbose_name': 'Función', 'verbose_name_plural': 'Funciones'},
        ),
        migrations.RemoveField(
            model_name='screening',
            name='price',
        ),
        migrations.AddField(
            model_name='screening',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.format', verbose_name='Formato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.language', verbose_name='Idioma'),
            preserve_default=False,
        ),
    ]
